# -*- coding: utf-8 -*-
"""Assignment #3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FUlEQhXyy-ue_aYK7FyRAEHuccRgzItl
"""

import pandas as pd
from google.colab import files
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import numpy as np

#load grades.csv
df = pd.read_csv("grades.csv")
df

#Boxplot for weighted_total column
df_tot = pd.read_csv("grades.csv", usecols = [21])
df_tot.plot.box()

"""This boxplot calculates the min,max,and medium. this boxplot shows that the students are mostly above average"""

#multiple bar graph for 5 homework assignments for compare and contrast of students’ performance in these 5 assignments
df_HW = pd.DataFrame(df, columns = ['Homework 1 [Total Pts: 20 Score] |1293619',	'Homework 2 [Total Pts: 20 Score] |1297002',	'Homework 3 [Total Pts: 20 Score] |1301007',	'Homework 4 [Total Pts: 20 Score] |1308148',	'Homework 5 [Total Pts: 20 Score] |1311965'])
df_HW.plot.bar();

"""This bar graph shows us the points that each student recived on each homework assignment"""

#graph of your choice Histogram
plt.figure();

df['Final [Total Pts: 100 Score] |1313303'].diff().hist()

"""This histogram allows us to see the frequency of the points earned during the final. Based on the graph most students earned an above average grade"""

#Load SP500 index stock data
df_500 = pd.read_csv("SP500_ind.csv")
df_500

#(1) a multiple-line graph (or other appropriate graph of your choice) to compare and contrast the performance Apple Inc. and Microsoft over a period of time provided in the data set. Use the stock close price.
plt.figure()
ax = df_500.loc[490:730,['Symbol','Close']].plot()
Micro= df_500.loc[74984:75225,['Symbol','Close']].plot(ax = ax)
plt.show()
df_500.loc[490:730,['Symbol','Close']].plot()
df_500.loc[74984:75225,['Symbol','Close']].plot(color = 'orange')

"""due to the range being based by location its hard to distingish between the two graphs but, its intresting to see the Microsoft had a major decline"""

#(2) an area plot graph (or other appropriate graph of your choice) to compare and contrast the trading volume of the above two companies.
df_Vol = pd.read_csv("SP500_ind.csv", usecols = ['Symbol','Volume'])
ax = df_500.loc[490:730,['Symbol','Volume']].plot.area()
Micro =df_500.loc[74984:75225,['Symbol','Volume']].plot.area(ax = ax)
df_500.loc[490:730,['Symbol','Volume']].plot.area()
df_500.loc[74984:75225,['Symbol','Volume']].plot.area(color = 'orange')

"""The range has a similar problem however, we can see that Apple has a higher volume than Microsoft"""

#(3) a graph of your choice that compares at least three companies in certain way of your choice.
# Scatter plot
Apple = df_500[ df_500['Symbol'] == 'AAPL' ]
Micro = df_500[ df_500['Symbol'] == 'MSFT' ]
AA= df_500[ df_500['Symbol'] == 'AA' ]
ax= Apple.plot(kind='scatter',x='Open',y='Low',color='red')
Micro.plot(kind='scatter',x='Open',y='Low',color='blue',ax=ax)
AA.plot(kind='scatter',x='Open',y='Low',color='green',ax=ax)
plt.show()

"""We can see that the relation between open and low increades as more are sold low for all graphs"""